import type { Metadata } from "next";
import { Anton, Roboto, Livvic } from "next/font/google";
import "./globals.css";

const livvic = Livvic({
  subsets: ["latin", "latin-ext", "vietnamese"],
  weight: "400",
  display: "swap",
  variable: "--font-livvic",
});

const anton = Anton({
  subsets: ["latin", "latin-ext", "vietnamese"],
  weight: "400",
  display: "swap",
  variable: "--font-anton",
});

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${anton.variable} ${roboto.variable} ${livvic.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
